name: 'docker-build'
description: 'Docker build'

inputs:
  name:
    description: 'Override the image name instead of defaulting to the name of the repository'
    required: false
    type: string
    default: ""
  dockerfile:
    description: 'Dockerfile that will build the image'
    required: false
    type: string
    default: "Dockerfile"
  platforms:
    description: 'Specify one or more comma-separated platforms for which the image is to be built'
    required: false
    type: string
    default: "linux/amd64"
  context:
    description: 'Docker build context directory'
    required: false
    type: string
    default: "."
  buildArgs:
    description: 'Specify one or more comma-separated arguments to pass to the build'
    required: false
    type: string
    default: ""
  tagPostfix:
    description: 'Add a postfix to the versioned tag'
    required: false
    type: string
    default: ""
  additionalTags:
    description: 'Specify one or more comma-separated tags to additionally apply'
    required: false
    type: string
    default: ""
  publish:
    description: 'Should the docker image be published to the registry?'
    required: false
    type: boolean
    default: false
  registryHost:
    description: 'The docker registry host (required if publish=true)'
    required: false
    type: string
    default: "ghcr.io"
  username:
    description: 'The username of the docker registry (required if publish=true)'
    required: false
    type: string
    default: ""
  apiToken:
    description: 'The API token of the docker registry (required if publish=true)'
    required: false
    type: string
    default: ""

runs:
  using: composite

  steps:
    - name: Setup QEMU for multiplatform
      uses: docker/setup-qemu-action@v3

    - name: Setup Docker
      uses: docker/setup-buildx-action@v3
    
    - name: Run Docker build
      shell: bash
      run: ./shared-actions/docker-build/build_script.sh
      env:
        NAME: ${{ inputs.name }}
        DOCKERFILE: ${{ inputs.dockerfile }}
        PLATFORMS: ${{ inputs.platforms }}
        CONTEXT: ${{ inputs.context }}
        BUILD_ARGS: ${{ inputs.buildArgs }}
        TAG_POSTFIX: ${{ inputs.tagPostfix }}
        ADDITIONAL_TAGS: ${{ inputs.additionalTags }}
        PUBLISH: ${{ inputs.publish }}
        REGISTRY_HOST: ${{ inputs.registryHost }}
        REGISTRY_USERNAME: ${{ inputs.username }}
        REGISTRY_API_TOKEN: ${{ inputs.apiToken }}
