name: 'setup-env'
description: 'Set environment variables'

runs:
  using: composite

  steps:
    - name: Setup BRANCH envvar
      shell: bash
      run: |
        USE_BRANCH=$(([[ 'pull_request' = $GH_EVENT_NAME ]] && echo ${GITHUB_HEAD_REF} || [[ 'release' = $GH_EVENT_NAME ]] && echo "main" || echo ${GITHUB_REF#refs/heads/}) | tr / - | tr '[:upper:]' '[:lower:]')
        echo "BRANCH=$USE_BRANCH"
        echo "BRANCH=$USE_BRANCH" >> $GITHUB_ENV
      env:
        GH_EVENT_NAME: ${{ github.event_name }}

    - name: Setup IS_MAIN_BRANCH envvar
      shell: bash
      run: |
        USE_IS_MAIN_BRANCH=$([[ 'master' = $BRANCH || 'main' = $BRANCH || 'develop' = $BRANCH ]] && echo "true" || echo "false")
        echo "IS_MAIN_BRANCH=$USE_IS_MAIN_BRANCH"
        echo "IS_MAIN_BRANCH=$USE_IS_MAIN_BRANCH" >> $GITHUB_ENV

    - name: Setup PACKAGE_VERSION envvar
      shell: bash
      run: |
        USE_PACKAGE_VERSION=$(echo $GH_EVENT_RELEASE_TAG_NAME | sed 's/^v\(.*\)/\1/g')
        if [ "$USE_PACKAGE_VERSION" = "" ]; then
          USE_PACKAGE_VERSION="${BRANCH}-${GH_RUN_NUMBER}"
        fi
        echo "PACKAGE_VERSION=$USE_PACKAGE_VERSION"
        echo "PACKAGE_VERSION=$USE_PACKAGE_VERSION" >> $GITHUB_ENV
      env:
        GH_EVENT_RELEASE_TAG_NAME: ${{ github.event.release.tag_name }}
        GH_RUN_NUMBER: ${{ github.run_number }}

    - name: Setup REPO envvar
      shell: bash
      run: |
        echo "REPO=$GH_EVENT_REPO_NAME"
        echo "REPO=$GH_EVENT_REPO_NAME" >> $GITHUB_ENV
      env:
        GH_EVENT_REPO_NAME: ${{ github.event.repository.name }}
